exports.STANDARD_SHEET_STATUS = {
  PENDING: "PENDING",
  REVIEWING: "REVIEWING",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
};

exports.APPROVAL_CONFIRM_STATUS = {
  APPROVED: "APPROVED",
  CANCELED: "CANCELED",
};
